import draftobjects.base
from draftobjects.base import DraftObject as DraftObject

class Block(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...

class _Block(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
