import DraftVecUtils as DraftVecUtils
import FreeCAD as App
import draftobjects.base
from _typeshed import Incomplete
from draftobjects.base import DraftObject as DraftObject

class Clone(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def join(self, obj, shapes): ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def getSubVolume(self, obj, placement: Incomplete | None = ...): ...

class _Clone(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def join(self, obj, shapes): ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def getSubVolume(self, obj, placement: Incomplete | None = ...): ...
