import FreeCAD as App
import draftobjects.base
import draftutils.utils as utils
from draftobjects.base import DraftObject as DraftObject

class Ellipse(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...

class _Ellipse(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
