import FreeCAD as App
import draftobjects.base
from draftobjects.base import DraftObject as DraftObject

class Point(draftobjects.base.DraftObject):
    def __init__(self, obj, x: int = ..., y: int = ..., z: int = ...) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...

class _Point(draftobjects.base.DraftObject):
    def __init__(self, obj, x: int = ..., y: int = ..., z: int = ...) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
