import DraftGeomUtils as DraftGeomUtils
import FreeCAD as App
import draftobjects.base
from draftobjects.base import DraftObject as DraftObject

class Polygon(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...

class _Polygon(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
