import DraftGeomUtils as DraftGeomUtils
import DraftVecUtils as DraftVecUtils
import FreeCAD as App
import draftobjects.base
from draftobjects.base import DraftObject as DraftObject

class Wire(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def update_start_end(self, obj): ...

class _Wire(draftobjects.base.DraftObject):
    def __init__(self, obj) -> None: ...
    def execute(self, obj): ...
    def onChanged(self, obj, prop): ...
    def update_start_end(self, obj): ...
