import draftmake.make_wire as make_wire
import draftutils.utils as utils

def split(wire, newPoint, edgeIndex): ...
def split_closed_wire(wire, edgeIndex): ...
def splitClosedWire(wire, edgeIndex): ...
def split_open_wire(wire, newPoint, edgeIndex): ...
def splitOpenWire(wire, newPoint, edgeIndex): ...
