import draftviewproviders.view_base
from draftviewproviders.view_base import ViewProviderDraft as ViewProviderDraft

class ViewProviderPoint(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, obj) -> None: ...
    def onChanged(self, vobj, prop): ...
    def getIcon(self): ...
    def doubleClicked(self, vobj): ...

class _ViewProviderPoint(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, obj) -> None: ...
    def onChanged(self, vobj, prop): ...
    def getIcon(self): ...
    def doubleClicked(self, vobj): ...
