import draftutils.gui_utils as gui_utils
import draftviewproviders.view_base
from draftviewproviders.view_base import ViewProviderDraft as ViewProviderDraft

class ViewProviderDraftArray(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def resetColors(self, vobj): ...

class _ViewProviderDraftArray(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def resetColors(self, vobj): ...
