import FreeCAD as App
import FreeCADGui as Gui
import PySide.QtCore as QtCore
import PySide.QtGui as QtGui

class ViewProviderWorkingPlaneProxy:
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def claimChildren(self): ...
    def doubleClicked(self, vobj): ...
    def setupContextMenu(self, vobj, menu): ...
    def writeCamera(self): ...
    def writeState(self): ...
    def attach(self, vobj): ...
    def getDisplayModes(self, vobj): ...
    def getDefaultDisplayMode(self): ...
    def setDisplayMode(self, mode): ...
    def updateData(self, obj, prop): ...
    def onChanged(self, vobj, prop): ...
    def dumps(self): ...
    def loads(self, state): ...
