import FreeCADGui as Gui
import draftviewproviders.view_base
from draftviewproviders.view_base import ViewProviderDraft as ViewProviderDraft

class ViewProviderFacebinder(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def setEdit(self, vobj, mode): ...
    def unsetEdit(self, vobj, mode): ...

class _ViewProviderFacebinder(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def setEdit(self, vobj, mode): ...
    def unsetEdit(self, vobj, mode): ...
