import draftviewproviders.view_base
from draftviewproviders.view_base import ViewProviderDraft as ViewProviderDraft

class ViewProviderDraftLink(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def claimChildren(self): ...

class _ViewProviderDraftLink(draftviewproviders.view_base.ViewProviderDraft):
    def __init__(self, vobj) -> None: ...
    def getIcon(self): ...
    def claimChildren(self): ...
