import draftviewproviders.view_wire
from draftviewproviders.view_wire import ViewProviderWire as ViewProviderWire

class ViewProviderFillet(draftviewproviders.view_wire.ViewProviderWire):
    def __init__(self, vobj) -> None: ...
    def doubleClicked(self, vobj): ...
