import FreeCAD as FreeCAD

__url__: str

class FemMigrateApp:
    def find_module(self, fullname, path): ...
    def create_module(self, spec): ...
    def exec_module(self, module): ...
    def load_module(self, module): ...
